version: 2.1
description: Okode ngx

branches: &branches
  context: org-global

tags: &tags
  context: org-global
  filters:
    branches:
      ignore:
        - /.*/
    tags:
      only: /.*/

orbs:
  lib:
    jobs:
      test:
        executor: browsers
        steps:
          - build:
              package: false
      package:
        executor: node
        steps:
          - build:
              package: true
    commands:
      build:
        parameters:
          package:
            type: boolean
          project:
            type: string
        steps:
          - checkout
          - restore_cache:
              key: cache-npm-{{ arch }}-{{ .Environment.CIRCLE_JOB }}-{{ checksum "package-lock.json" }}
          - run:
              name: Installing NPM dependencies
              command: if [ ! -d "node_modules" ]; then npm ci; fi
          - when:
              condition: << parameters.package >>
              steps:
                - run:
                    name: Installing Angular CLI and NPM CLI Login
                    command: sudo npm install -g @angular/cli npm-cli-login
                - run:
                    name: Building
                    command: ng build @okode/<< parameters.project >>
                - run:
                    name: Authenticating NPM
                    command: npm-cli-login
                - run:
                    name: Publishing NPM package
                    command: cd dist/<< parameters.project >> && npm publish --access=public
          - unless:
              condition: << parameters.package >>
              steps:
                - run:
                    name: Installing Angular CLI
                    command: sudo npm install -g @angular/cli
                - run:
                    name: Building
                    command: ng build @okode/<< parameters.project >>
                - run:
                    name: Running unit tests
                    command: ng test @okode/<< parameters.project >> --watch false --progress false
          - run:
              name: Restoring package-lock.json
              command: git checkout package-lock.json
          - save_cache:
              key: cache-npm-{{ arch }}-{{ .Environment.CIRCLE_JOB }}-{{ checksum "package-lock.json" }}
              paths:
                - node_modules

    executors:
      browsers:
        docker:
          - image: circleci/node:11-browsers
      node:
        docker:
          - image: circleci/node:11

workflows:
  workflow:
    jobs:
      - lib/test:
          <<: *branches
          name: test-common
          project: common
      - lib/package:
          <<: *tags
          name: package-common
          project: common
      - lib/test:
          <<: *branches
          name: test-components
          project: components
      - lib/package:
          <<: *tags
          name: package-components
          project: components
      - lib/test:
          <<: *branches
          name: test-custom-palette
          project: custom-palette
      - lib/package:
          <<: *tags
          name: package-custom-palette
          project: custom-palette