version: 2.1

orbs:
  aws-s3: circleci/aws-s3@1.0.7

jobs:
  build:
    docker:
      - image: circleci/node:11
    steps:
      - checkout
      - restore_cache:
          key: cache-01-npm-{{ arch }}-{{ .Environment.CIRCLE_JOB }}-{{ checksum "package-lock.json" }}
      - run:
          name: Installing NPM dependencies
          command: if [ ! -d "node_modules" ]; then npm ci; fi
      - run:
          name: Building ngx
          command: npm run build
      - run:
          name: Building docs
          command: npm run doc
      - run:
          name: Copying docs
          command: cp -R documentation www
      - persist_to_workspace:
          root: .
          paths:
            - www
      - run:
          name: Restoring package-lock.json
          command: git checkout package-lock.json
      - save_cache:
          key: cache-01-npm-{{ arch }}-{{ .Environment.CIRCLE_JOB }}-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - aws-s3/sync:
          from: /tmp/workspace/www
          to: s3://ngx-doc
          arguments: --acl public-read
          overwrite: true

workflows:
  default:
    jobs:
      - build:
          context: org-global
          filters:
            branches:
              ignore:
                - master